services:
  n8n:
    build:
      context: ../MCP-Server
      dockerfile: Dockerfile
    container_name: n8n-mcp
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=medi-bot-admin-2024
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true
      - N8N_DISABLE_UI=false
      - N8N_WEBHOOK_URL=http://localhost:5678
      - N8N_WORKFLOWS_ENABLE_ON_STARTUP=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    volumes:
      - ../MCP-Server:/home/node/.n8n
