services:
  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    image: medi-bot-backend
    container_name: medi-bot-backend
    environment:
      - BACKEND_HOST=${BACKEND_HOST:-0.0.0.0}
      - BACKEND_PORT=${BACKEND_PORT:-8000}
      - BACKEND_API_ENDPOINT=${BACKEND_API_ENDPOINT:-/api}
      - LLM_SERVER_MODEL=${LLM_SERVER_MODEL:-gpt-4o-mini}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - EXTERNAL_SERVICE_URL=${EXTERNAL_SERVICE_URL:-localhost}
      - CHROMADB_HOST=${CHROMADB_HOST:-chromadb_server}
      - CHROMADB_PORT=${CHROMADB_PORT:-5000}
      - CHROMADB_EXTERNAL_PORT=${CHROMADB_EXTERNAL_PORT:-5001}
      - CHROMADB_USER=${CHROMADB_USER:-admin}
      - MCP_SERVER_URL=${MCP_SERVER_URL:-http://localhost:3000}
    ports:
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
    volumes:
      - ../Backend:/app
      - ../vector-db:/app/vector-db
    depends_on:
      - chromadb
    networks:
      - medi-bot-network
    restart: unless-stopped

  chromadb:
    build:
      context: ../Data-ingestor
      dockerfile: Dockerfile
    image: chroma_db
    container_name: chromadb_server
    environment:
      - CHROMADB_PORT=${CHROMADB_PORT}
      - CHROMADB_HOST=${CHROMADB_HOST}
      - CHROMADB_EXTERNAL_PORT=${CHROMADB_EXTERNAL_PORT}
      - CHROMADB_COLLECTION=${CHROMADB_COLLECTION}
      - OTEL_SDK_DISABLED=true
      - CHROMA_OTEL_ENABLED=false
      - OTEL_TRACES_EXPORTER=none
      - OTEL_METRICS_EXPORTER=none
    ports:
      - "${CHROMADB_EXTERNAL_PORT}:${CHROMADB_PORT}"
    volumes:
      - ../Data-ingestor/data:/app/data
      - ../vector-db/chroma:/app/chroma
    networks:
      - medi-bot-network
    restart: unless-stopped

networks:
  medi-bot-network:
    driver: bridge

